<#
.SYNOPSIS
  Build and serve the DeepSeek Harness Web application for LAN access.

.DESCRIPTION
  Builds only what the Web profile serves - host libraries, dynamic client bundles, and the
  Web shell dist - then starts the server with a patch overlay that restates the webserver
  row. The overlay is the supported way to bind a non-loopback address: "dsh web --host
  0.0.0.0" is refused by design.

  Access is authenticated by the token printed at startup. The server exchanges it for a
  signed cookie scoped to the request authority, so one visit with the token URL keeps that
  browser working across server restarts (the signing secret is durable); another host name
  or IP is another authority and needs the token again.

.PARAMETER BindHost
  Address the server binds. Use this machine LAN address, or 0.0.0.0 to bind every
  interface. Binding every interface exposes the agent to the whole network: anyone holding
  the token URL or a live cookie can run tools as this account.

.PARAMETER Port
  Listen port. Default 3080, the Web profile own default.

.PARAMETER TrustedHost
  Extra authority the /api browser-trust fence accepts (host or host:port). The fence already
  accepts this machine LAN addresses; add one for a DNS name or a reverse proxy.

.PARAMETER SkipBuild
  Skip the build and serve the artifacts already in the tree.

.EXAMPLE
  .\serve-dsh-web.ps1
  Build, then serve on every interface at the default port.

.EXAMPLE
  .\serve-dsh-web.ps1 -BindHost 127.0.0.1 -Port 3080 -SkipBuild
  Serve locally without rebuilding.
#>
[CmdletBinding()]
param(
  [string] $BindHost = '0.0.0.0',
  [ValidateRange(1, 65535)]
  [int] $Port = 3080,
  [string[]] $TrustedHost = @(),
  [switch] $SkipBuild
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repo = $PSScriptRoot
Set-Location $repo
$overlayName = 'serve-dsh-web.overlay.yml'
$overlay = Join-Path $repo $overlayName

function Write-Step([string] $message) {
  Write-Host ''
  Write-Host "==> $message" -ForegroundColor Cyan
}

function Invoke-Pnpm([string[]] $arguments) {
  Write-Host ("    pnpm " + ($arguments -join ' ')) -ForegroundColor DarkGray
  # pnpm writes progress and warnings to stderr, and ErrorActionPreference Stop would turn
  # those into terminating errors; failures are read from the exit code instead.
  $previous = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  try { & pnpm @arguments } finally { $ErrorActionPreference = $previous }
  if ($LASTEXITCODE -ne 0) { throw "pnpm $($arguments -join ' ') failed with exit code $LASTEXITCODE" }
}

# --- Preconditions -------------------------------------------------------------------------
$manifest = Join-Path $repo 'package.json'
if (-not (Test-Path $manifest)) { throw "not a repository root: $manifest is missing" }
$name = (Get-Content $manifest -Raw | ConvertFrom-Json).name
if ($name -ne '@deepseek-ai/dsh-root') { throw "unexpected root package: $name" }
foreach ($tool in @('node', 'pnpm')) {
  if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) { throw "$tool is not on PATH" }
}

# The client build record rejects a missing or stale commit; a git-less checkout needs one.
$gitCommit = $null
if (Test-Path (Join-Path $repo '.git')) {
  $gitCommit = (& git -C $repo rev-parse HEAD 2>$null | Select-Object -First 1)
}
if ($gitCommit -match '^[0-9a-fA-F]{40}$') {
  $env:DSH_CLIENT_COMMIT_HASH = $gitCommit.Substring(0, 7).ToLowerInvariant()
  $env:DSH_DESKTOP_BUILD_COMMIT = $gitCommit.ToLowerInvariant()
  Write-Step "Repository $repo (commit $($env:DSH_CLIENT_COMMIT_HASH))"
} else {
  if (-not $env:DSH_CLIENT_COMMIT_HASH) { $env:DSH_CLIENT_COMMIT_HASH = '0000000' }
  Write-Step "Repository $repo (no .git; using DSH_CLIENT_COMMIT_HASH=$($env:DSH_CLIENT_COMMIT_HASH))"
}

if (-not $SkipBuild) {
  Write-Step 'Building the Web form (host libraries, client bundles, Web dist)'
  Invoke-Pnpm @('run', 'build:lib:host')
  Invoke-Pnpm @('run', 'build:lib:client')
  Invoke-Pnpm @('run', 'build:web')
}

# --- Deployment binding --------------------------------------------------------------------
# A patch replaces the targeted row's whole config, so every key the row owns is restated.
$overlayText = @"
# Generated by serve-dsh-web.ps1: the deployment binding for this machine.
- id: webserver
  config:
    host: '$BindHost'
    port: $Port
    compression: gzip
    compressionLevel: 1
    compressionThresholdBytes: 1024
"@
Set-Content -Path $overlay -Value $overlayText -Encoding utf8

# Keep the generated overlay out of git status without touching the tracked ignore file.
$exclude = Join-Path $repo '.git\info\exclude'
if (Test-Path $exclude) {
  $entries = @(Get-Content $exclude -ErrorAction SilentlyContinue)
  if ($entries -notcontains $overlayName) { Add-Content -Path $exclude -Value $overlayName }
}
Write-Step ("Serving on " + $BindHost + ":" + $Port)

if ($BindHost -eq '0.0.0.0') {
  Write-Host '    binding every interface: any LAN peer holding the token URL or a live cookie can run tools as this account' -ForegroundColor Yellow
  Write-Host '    put TLS and an address allowlist in front of it (reverse proxy) for anything beyond a trusted LAN' -ForegroundColor Yellow
}

$arguments = @('dsh', '--profile', 'web', '--patch', $overlayName, '--no-open')
foreach ($authority in $TrustedHost) { $arguments += @('--trusted-host', $authority) }
Write-Host ("    pnpm " + ($arguments -join ' ')) -ForegroundColor DarkGray
# The server writes its banner line to stderr, and ErrorActionPreference Stop would end the
# script on that first line; the server itself runs until it is stopped.
$previous = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
try { & pnpm @arguments } finally { $ErrorActionPreference = $previous }
